services:
  # Application (PHP-FPM) - SUBDIRECTORY CONFIGURATION
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: staging
    container_name: controle-financeiro-app-subdirectory
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - app_storage:/var/www/html/storage
      - app_cache:/var/www/html/bootstrap/cache
      - app_logs:/var/www/html/storage/logs
      - ./docker/php/php-staging.ini:/usr/local/etc/php/conf.d/99-custom.ini
      - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    environment:
      - APP_ENV=staging
      - APP_DEBUG=false
      - APP_URL=${APP_URL:-https://dev.nexxtecnologia.com.br/Controle-Financeiro}
      - ASSET_URL=${ASSET_URL:-https://dev.nexxtecnologia.com.br/Controle-Financeiro}
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE:-controle_financeiro_staging}
      - DB_USERNAME=${DB_USERNAME:-staging_user}
      - DB_PASSWORD=${DB_PASSWORD}
      - CACHE_DRIVER=file
      - SESSION_DRIVER=file
      - SESSION_PATH=${SUBDIRECTORY_PATH:-/Controle-Financeiro}
      - QUEUE_CONNECTION=database
      - LOG_CHANNEL=stack
      - LOG_LEVEL=info
      - LOG_STDERR_FORMATTER=Monolog\Formatter\JsonFormatter
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - controle-financeiro-network
    healthcheck:
      test: ["CMD", "php", "artisan", "health:check", "--detailed", "--no-interaction"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Web Server (NGINX) - SUBDIRECTORY WITH PORT MAPPING
  nginx:
    image: nginx:alpine
    container_name: controle-financeiro-nginx-subdirectory
    restart: unless-stopped
    ports:
      - "8080:80"  # Map to port 8080 on host
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/nginx-staging.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/subdirectory.conf:/etc/nginx/conf.d/default.conf
      - nginx_logs:/var/log/nginx
    depends_on:
      - app
    networks:
      - controle-financeiro-network
    environment:
      - NGINX_HOST=${NGINX_HOST:-dev.nexxtecnologia.com.br}
      - NGINX_PORT=80
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/Controle-Financeiro/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=nginx,environment=subdirectory"

  # Database (MySQL) - SUBDIRECTORY CONFIGURATION
  mysql:
    image: mysql:8.0
    container_name: controle-financeiro-mysql-subdirectory
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE:-controle_financeiro_staging}
      MYSQL_USER: ${DB_USERNAME:-staging_user}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_INITDB_SKIP_TZINFO: 1
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_logs:/var/log/mysql
      - ./docker/mysql/staging.cnf:/etc/mysql/conf.d/staging.cnf
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3307:3306"  # Map to port 3307 to avoid conflicts
    networks:
      - controle-financeiro-network
    command: --default-authentication-plugin=mysql_native_password --log-error-verbosity=2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        labels: "service=mysql,environment=subdirectory"

  # Queue Worker - SUBDIRECTORY CONFIGURATION
  queue:
    build:
      context: .
      dockerfile: Dockerfile
      target: staging
    container_name: controle-financeiro-queue-subdirectory
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - app_storage:/var/www/html/storage
      - app_logs:/var/www/html/storage/logs
    environment:
      - APP_ENV=staging
      - APP_DEBUG=false
      - APP_URL=${APP_URL:-https://dev.nexxtecnologia.com.br/Controle-Financeiro}
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE:-controle_financeiro_staging}
      - DB_USERNAME=${DB_USERNAME:-staging_user}
      - DB_PASSWORD=${DB_PASSWORD}
      - QUEUE_CONNECTION=database
      - LOG_CHANNEL=stack
      - LOG_LEVEL=info
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600 --memory=512 --timeout=300
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - controle-financeiro-network
    healthcheck:
      test: ["CMD", "php", "artisan", "queue:monitor", "--max-wait=60"]
      interval: 60s
      timeout: 30s
      retries: 3
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Scheduler (Cron) - SUBDIRECTORY CONFIGURATION
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
      target: staging
    container_name: controle-financeiro-scheduler-subdirectory
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - app_storage:/var/www/html/storage
      - app_logs:/var/www/html/storage/logs
    environment:
      - APP_ENV=staging
      - APP_DEBUG=false
      - APP_URL=${APP_URL:-https://dev.nexxtecnologia.com.br/Controle-Financeiro}
      - DB_HOST=mysql
      - DB_DATABASE=${DB_DATABASE:-controle_financeiro_staging}
      - DB_USERNAME=${DB_USERNAME:-staging_user}
      - DB_PASSWORD=${DB_PASSWORD}
      - LOG_CHANNEL=stack
      - LOG_LEVEL=info
    command: sh -c "while true; do php artisan schedule:run --verbose; sleep 60; done"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - controle-financeiro-network
    healthcheck:
      test: ["CMD", "php", "artisan", "schedule:list"]
      interval: 300s
      timeout: 30s
      retries: 2
      start_period: 60s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mysql_data:
    driver: local
  app_storage:
    driver: local
  app_cache:
    driver: local
  app_logs:
    driver: local
  mysql_logs:
    driver: local
  nginx_logs:
    driver: local

networks:
  controle-financeiro-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16  # Different subnet to avoid conflicts